from pysc2.lib import actions
from pysc2.lib import features

# Functions
BUILD_SUPPLY_DEPOT = actions.FUNCTIONS.Build_SupplyDepot_screen.id
BUILD_BARRACKS = actions.FUNCTIONS.Build_Barracks_screen.id
SELECT_POINT = actions.FUNCTIONS.select_point.id
SELECT_RECT = actions.FUNCTIONS.select_rect.id
SELECT_IDLE_WORKER = actions.FUNCTIONS.select_idle_worker.id
SELECT_ARMY = actions.FUNCTIONS.select_army.id
HARVEST_GATHER_SCREEN = actions.FUNCTIONS.Harvest_Gather_screen.id
MOVE_SCREEN = actions.FUNCTIONS.Move_screen.id
SMART_SCREEN = actions.FUNCTIONS.Smart_screen.id
TRAIN_SCV_QUICK = actions.FUNCTIONS.Train_SCV_quick.id
NO_OP = actions.FUNCTIONS.no_op.id

# Features
PLAYER_RELATIVE = features.SCREEN_FEATURES.player_relative.index
UNIT_TYPE = features.SCREEN_FEATURES.unit_type.index
HEIGHT_MAP = features.SCREEN_FEATURES.height_map.index

# Units ID
TERRAN_COMMAND_CENTER = 18
TERRAN_SCV = 45
MINERAL_FIELD = 341
MINERAL_FIELD_750 = 483
RICH_MINERAL_FIELD = 146
RICH_MINERAL_FIELD_750 = 147
ALL_MINERAL_FIELD = (MINERAL_FIELD, MINERAL_FIELD_750, RICH_MINERAL_FIELD, RICH_MINERAL_FIELD_750)
VESPENE_GEYSER = 342
RICH_VESPENE_GEYSER = 344
ALL_VESPENE_GEYSER = (VESPENE_GEYSER, RICH_VESPENE_GEYSER)

# Parameters
PLAYER_SELF = 1
PLAYER_NEUTRAL = 3
NOT_QUEUED = [False]
QUEUED = [True]
NEW_SELECTION = [0]
SELECT_ALL = [0]

# Others
SCREEN_RESOLUTION = 84
MAX_COLLECTING_DISTANCE = SCREEN_RESOLUTION / 3
TILES_SIZE_IN_CELL = SCREEN_RESOLUTION / 21

# Observation index
# 'player' indexes
PLAYER_ID = 0
MINERALS = 1
VESPENE = 2
FOOD_USED = 3
FOOD_CAP = 4
FOOD_USED_BY_ARMY = 5
FOOD_USED_BY_WORKERS = 6
IDLE_WORKER_COUNT = 7
ARMY_COUNT = 8
WARP_GATE_COUNT = 9
LARVA_COUNT = 10
